---
- name: Install nginx package
  ansible.builtin.apt:
    name: nginx
    state: present
  tags:
    - nginx

- name: Configure nginx.conf
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - {src: nginx.conf.j2, dest: /etc/nginx/nginx.conf}
    - {src: default.nginx.j2, dest: /etc/nginx/sites-enabled/default}
  notify: Restart nginx
  tags:
    - nginx

- name: Remove original default vhost
  ansible.builtin.file:
    path: /etc/nginx/sites-available/default
    state: absent
  tags:
    - nginx

- name: Setuo static sites
  when: static_sites is defined
  tags:
    - nginx
  block:
    - name: Configure static sites directory
      ansible.builtin.file:
        path: "{{ nginx.root_base_path }}/sites"
        state: directory
        owner: root
        group: root
        mode: 0755
      notify: Restart nginx
    - name: Configure static sites subdirectories
      ansible.builtin.file:
        path: "{{ nginx.root_base_path }}/sites/{{ item.server_name }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ static_sites }}"
      notify: Restart nginx

    - name: Configure nginx virtual hosts
      ansible.builtin.template:
        src: static-vhost.conf.j2
        dest: "/etc/nginx/sites-enabled/{{ item.server_name }}-static.conf"
        owner: root
        group: root
        mode: 0644
      loop: "{{ static_sites }}"
      notify: Restart nginx
