---
- name: install package
  apt:
    name: nginx
    state: present
  tags:
    - nginx

- name: remove original default vhost
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  tags:
    - nginx

- name: setup nginx.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
    - { src: default.nginx.j2, dest: /etc/nginx/sites-enabled/default }
  notify: restart nginx
  tags:
    - nginx

- block:
    - name: setup static sites directory
      file:
        path: "{{ nginx.root_base_path }}/sites"
        state: directory
        owner: root
        group: root
        mode: 0755
      notify: restart nginx
      tags:
        - nginx

    - name: setup static sites subdirectories
      file:
        path: "{{ nginx.root_base_path }}/sites/{{ item.server_name }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ static_sites }}"
      notify: restart nginx
      tags:
        - nginx

    - name: setup nginx virtual hosts
      template:
        src: static-vhost.conf.j2
        dest: "/etc/nginx/sites-enabled/{{ item.server_name }}-static.conf"
        owner: root
        group: root
        mode: 0644
      loop: "{{ static_sites }}"
      notify: restart nginx
      tags:
        - nginx
  when: static_sites is defined
