---
- name: install package
  apt:
    name: nginx
    state: present
  tags:
    - nginx

- name: remove original default vhost
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  tags:
    - nginx

- name: setup nginx.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
    - { src: default.nginx.j2, dest: /etc/nginx/sites-enabled/default }
  notify: restart nginx
  tags:
    - nginx
