---
- name: Setup static sites
  tags:
    - nginx
  block:
    - name: Configure static sites directory
      ansible.builtin.file:
        path: "{{ nginx_static_sites_root_dir }}/sites"
        state: directory
        owner: root
        group: root
        mode: "0755"
      notify: Restart nginx

    - name: Configure static sites subdirectories
      ansible.builtin.file:
        path: "{{ nginx_static_sites_root_dir }}/sites/{{ item.server_name }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop: "{{ nginx_static_sites }}"
      notify: Restart nginx

    - name: Configure nginx virtual hosts
      ansible.builtin.template:
        src: nginx-static.conf.j2
        dest: "{{ nginx_conf_inc_dir }}/{{ item.server_name }}-static.conf"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ nginx_static_sites }}"
      notify: Restart nginx
