---
- name: setup raspberry pi
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - base
    - security
    - firewall
    - dnscrypt-proxy
    - nginx
    - navidrome
    - minidlna
    - samba
