---
- name: Configure raspberry pi
  hosts: all
  become: true
  vars_files:
    - vars.yml
  roles:
    - base
    - security
    - firewall
    - dnscrypt_proxy
    - nginx
    - navidrome
    - minidlna
    - samba
