---
- name: Configure raspberry pi
  hosts: router
  become: true
  vars_files:
    - vars-router.yml
  roles:
    - core
    - sysctl
    - suricata
    - evebox
    - firewall
    - dnscrypt_proxy
    - nginx
    - navidrome
    - minidlna
    - samba
    - user
