---
- name: Configure .bashrc
  ansible.builtin.template:
    src: bashrc.j2
    dest: "{{ user_home }}/.bashrc"
    owner: "{{ user_login }}"
    group: "{{ user_group }}"
    mode: "0600"
  tags:
    - user
