---
- name: Configure .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ user_home }}/.gitconfig"
    owner: "{{ user_login }}"
    group: "{{ user_groups | first }}"
    mode: "0644"
  tags:
    - user
