---
- name: Configure group
  ansible.builtin.group:
    name: "{{ user_group }}"
    state: present
  tags:
    - user

- name: Configure user
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: ["users", "{{ user_group }}", "sudo"]
    state: present
  tags:
    - user

- name: Configure .bashrc
  ansible.builtin.template:
    src: bashrc.j2
    dest: "{{ user_home }}/.bashrc"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0600
  tags:
    - user
