---
- name: Configure group
  ansible.builtin.group:
    name: "{{ user_groups | first }}"
    state: present
  tags:
    - user

- name: Configure user
  ansible.builtin.user:
    name: "{{ user_login }}"
    groups: "{{ user_groups }}"
    state: present
  tags:
    - user

- name: Configure .bashrc
  ansible.builtin.template:
    src: bashrc.j2
    dest: "{{ user_home }}/.bashrc"
    owner: "{{ user_login }}"
    group: "{{ user_groups | first }}"
    mode: 0600
  tags:
    - user

- name: Configure .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ user_home }}/.gitconfig"
    owner: "{{ user_login }}"
    group: "{{ user_groups | first }}"
    mode: 0644
  tags:
    - user
