---
- name: Configure system
  ansible.builtin.import_tasks: system.yml
  tags:
    - user

- name: Configure fish
  ansible.builtin.import_tasks: fish.yml
  tags:
    - user

- name: Configure bash
  ansible.builtin.import_tasks: bash.yml
  tags:
    - user

- name: Configure git
  ansible.builtin.import_tasks: git.yml
  tags:
    - user
