---
- name: Configure group
  ansible.builtin.group:
    name: "{{ user_group }}"
    state: present
  tags:
    - user

- name: Configure user
  ansible.builtin.user:
    name: "{{ user_login }}"
    groups: "{{ user_groups }}"
    state: present
  tags:
    - user
