---
- name: Daemon-reload
  ansible.builtin.systemd:
    daemon-reload: true

- name: Restart dhcpcd
  ansible.builtin.systemd:
    name: dhcpcd
    state: restarted

- name: Restart dhcpd
  ansible.builtin.systemd:
    name: isc-dhcp-server
    state: restarted

- name: Restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
