---
- name: Daemon-reload
  ansible.builtin.systemd:
    daemon-reload: true

- name: Generate locales
  ansible.builtin.command: locale-gen
  tags:
    - base

- name: Restart dhcpcd
  ansible.builtin.systemd:
    name: dhcpcd
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
