---
- name: Disable unwanted services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ core_disabled_services }}"
  when: core_disabled_services is iterable
  tags:
    - core

- name: Configure boot/config.txt
  ansible.builtin.template:
    src: boot-config.txt.j2
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0755
  tags:
    - core

- name: Configure sshd
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Restart sshd
  tags:
    - core

- name: Configure correct timezone
  community.general.timezone:
    name: Europe/Prague
  tags:
    - core

- name: Configure locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - en_US.UTF-8
    - cs_CZ.UTF-8
  notify: Generate locales
  tags:
    - core

- name: Configure /etc/default/locale
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    line: "LANG=en_US.UTF-8"
    regexp: LANG
    create: true
    state: present
    owner: root
    group: root
    mode: 0644
  tags:
    - core

- name: Set machine hostname
  ansible.builtin.hostname:
    name: "{{ network.hostname }}"
  tags:
    - core
    - dns

- name: Remove /etc/resolvconf.conf
  ansible.builtin.file:
    path: /etc/resolvconf.conf
    state: absent
  tags:
    - core
    - dns

- name: Configure resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart dhcpcd
  tags:
    - core
    - dns

- name: Configure /etc/nsswitch.conf
  ansible.builtin.template:
    src: nsswitch.conf.j2
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - core
    - dns

- name: Set hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - core
    - dns

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart chrony
  tags:
    - core

- name: Configure dhcpd.conf
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart dhcpd
  tags:
    - core

- name: Download http://standards-oui.ieee.org/oui.txt
  ansible.builtin.uri:
    url: http://standards-oui.ieee.org/oui.txt
    dest: /usr/local/etc/oui.txt
    owner: root
    group: root
    mode: 0644
  notify: Restart dhcpd
  tags:
    - core

- name: Configure ENV variables
  ansible.builtin.template:
    src: vars.sh.j2
    dest: /etc/profile.d/vars.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - core

- name: Configure sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
    insertafter: "%sudo.+ALL"
    regexp: "NOPASSWD:.+ALL"
    state: present
  tags:
    - core
    - user

- name: Prepare mount points
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ mount.points }}"
  when: mount.points is defined
  tags:
    - core
