---
# FIXME: quick and dirty support for both 4 and 5

- name: Configure | boot/config.txt
  ansible.builtin.template:
    src: boot-config4.txt.j2
    dest: /boot/config.txt
    owner: root
    group: root
    mode: "0755"
  when:
    - raspberry_version is defined
    - raspberry_version == 4
  tags:
    - core
    - boot_config

- name: Configure | boot/firmware/config.txt
  ansible.builtin.template:
    src: boot-config5.txt.j2
    dest: /boot/firmware/config.txt
    owner: root
    group: root
    mode: "0755"
  when:
    - raspberry_version is defined
    - raspberry_version == 5
  tags:
    - core
    - boot_config

# ---

- name: Configure | sshd
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd
  tags:
    - core
    - sshd

- name: Configure | ENV variables
  ansible.builtin.template:
    src: vars.sh.j2
    dest: /etc/profile.d/vars.sh
    owner: root
    group: root
    mode: "0755"
  tags:
    - core
    - env
