---
- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: true
    state: absent
  loop: "{{ core_absent_packages }}"
  when: core_absent_packages is iterable
  tags:
    - core

- name: Install necessary packages
  ansible.builtin.apt:
    name: "{{ core_packages }}"
    state: present
    update_cache: true
  when: core_packages is iterable
  tags:
    - core

- name: Download yt-dlp
  ansible.builtin.get_url:
    url: "https://github.com/yt-dlp/yt-dlp/releases/download/{{ yt_dlp_version }}/yt-dlp_linux_aarch64"
    dest: /usr/local/bin/yt-dlp
    owner: root
    group: root
    mode: 0755
  tags:
    - core
