---
- name: Configure correct timezone
  community.general.timezone:
    name: Europe/Prague
  tags:
    - core
    - time

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart chrony
  tags:
    - core
    - time
