---
- name: Set facts
  ansible.builtin.set_fact:
    navidrome_tarball: "navidrome_{{ navidrome.version }}_linux_arm64.tar.gz"
  tags:
    - navidrome

- name: Download release from github
  ansible.builtin.get_url:
    url: "https://github.com/navidrome/navidrome/releases/download/v{{ navidrome.version }}/{{ navidrome_tarball }}"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
  tags:
    - navidrome

- name: Prepare directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: navidrome
    group: users
    mode: 0700
  loop:
    - "{{ navidrome.working_directory }}"
    - "{{ navidrome.bin_directory }}"
  tags:
    - navidrome

- name: Configure navidrome user
  ansible.builtin.user:
    name: navidrome
    groups: [ "users" ]
    shell: /usr/sbin/nologin
    home: "{{ navidrome.working_directory }}"
    state: present
  tags:
    - navidrome

- name: Extract archive
  ansible.builtin.unarchive:
    src: /tmp/{{ navidrome_tarball }}
    dest: /opt/navidrome
    remote_src: true
  notify: Restart navidrome
  when: not ansible_check_mode
  tags:
    - navidrome

- name: Configure navidrome.toml
  ansible.builtin.template:
    src: navidrome.toml.j2
    dest: "{{ navidrome.working_directory }}/navidrome.toml"
    owner: navidrome
    group: users
    mode: 0755
  notify: Restart navidrome
  tags:
    - navidrome

- name: Configure navidrome.service
  ansible.builtin.template:
    src: navidrome.service.j2
    dest: /etc/systemd/system/navidrome.service
    owner: root
    group: root
    mode: 0755
  notify:
    - Daemon-reload
    - Restart navidrome
  tags:
    - navidrome

- name: Configure nginx virtualhost
  ansible.builtin.template:
    src: navidrome.nginx.conf.j2
    dest: "{{ nginx_conf_inc_dir }}/navidrome.conf"
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx
  tags:
    - navidrome
    - nginx

- name: Install ffmpeg
  ansible.builtin.apt:
    name: ffmpeg
    state: present
  tags:
    - navidrome
