---
- name: Prepare directory for blocklist generator and its config
  ansible.builtin.file:
    path: "{{ dnscrypt_proxy_blocked_names_generator_path }}"
    state: directory
    owner: root
    group: root
    mode: 0500

- name: Download blocklist generator
  ansible.builtin.get_url:
    url: https://github.com/DNSCrypt/dnscrypt-proxy/raw/master/utils/generate-domains-blocklist/generate-domains-blocklist.py
    dest: "{{ dnscrypt_proxy_blocked_names_generator_path }}/generate-domains-blocklist.py"
    owner: root
    group: root
    mode: 0400
  notify: Generate blocked names

- name: Configure domains-blocklist.conf
  ansible.builtin.template:
    src: domains-blocklist.conf.j2
    dest: "{{ dnscrypt_proxy_blocked_names_generator_path }}/domains-blocklist.conf"
    owner: root
    group: root
    mode: 0400
  notify: Generate blocked names

- name: Configure domains-blocklist-local-additions.txt
  ansible.builtin.template:
    src: domains-blocklist-local-additions.txt.j2
    dest: "{{ dnscrypt_proxy_blocked_names_generator_path }}/domains-blocklist-local-additions.txt"
    owner: root
    group: root
    mode: 0400
  notify: Generate blocked names

- name: Configure domains-allowlist.txt from github
  ansible.builtin.get_url:
    url: https://github.com/DNSCrypt/dnscrypt-proxy/raw/master/utils/generate-domains-blocklist/domains-allowlist.txt
    dest: "{{ dnscrypt_proxy_blocked_names_generator_path }}/domains-allowlist.txt"
    owner: root
    group: root
    mode: 0400
  notify: Generate blocked names

- name: Create empty domains-time-restricted.txt
  ansible.builtin.file:
    dest: "{{ dnscrypt_proxy_blocked_names_generator_path }}/domains-time-restricted.txt"
    state: touch
    owner: root
    group: root
    mode: 0400

- name: Configure helper script
  ansible.builtin.template:
    src: blocked-names-generator.sh.j2
    dest: "{{ dnscrypt_proxy_blocked_names_generator_helper_path }}"
    owner: root
    group: root
    mode: 0500
  notify: Generate blocked names

- name: Configure cron script
  ansible.builtin.template:
    src: cron.j2
    dest: /etc/cron.daily/blocked-names-generator
    owner: root
    group: root
    mode: 0500
