---
- name: Configure dnscrypt-proxy
  ansible.builtin.template:
    src: dnscrypt-proxy.toml.j2
    dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
    owner: root
    group: root
    mode: 0444
  notify: Restart dnscrypt-proxy

- name: Configure allowed-names.txt
  ansible.builtin.template:
    src: allowed-names.txt.j2
    dest: /etc/dnscrypt-proxy/allowed-names.txt
    owner: root
    group: root
    mode: 0444
  when: dnscrypt_proxy.allowed_names is defined
  notify: Restart dnscrypt-proxy

- name: Configure blocked-ips.txt
  ansible.builtin.template:
    src: blocked-ips.txt.j2
    dest: /etc/dnscrypt-proxy/blocked-ips.txt
    owner: root
    group: root
    mode: 0444
  notify: Restart dnscrypt-proxy

- name: Configure forwarding-rules.txt
  ansible.builtin.template:
    src: forwarding-rules.txt.j2
    dest: /etc/dnscrypt-proxy/forwarding-rules.txt
    owner: root
    group: root
    mode: 0444
  when: dnscrypt_proxy.forwarding_rules is defined
  notify: Restart dnscrypt-proxy

- name: Configure cloaking-rules.txt
  ansible.builtin.template:
    src: cloaking-rules.txt.j2
    dest: /etc/dnscrypt-proxy/cloaking-rules.txt
    owner: root
    group: root
    mode: 0444
  when: dnscrypt_proxy.cloaking_rules is defined
  notify: Restart dnscrypt-proxy

- name: Set permissions to /etc/dnscrypt-proxy
  ansible.builtin.file:
    path: /etc/dnscrypt-proxy
    state: directory
    owner: root
    group: root
    mode: 0555
