---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ dnscrypt_proxy_conf_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0555"

- name: Configure dnscrypt-proxy
  ansible.builtin.template:
    src: dnscrypt-proxy.toml.j2
    dest: "{{ dnscrypt_proxy_conf_dir }}/dnscrypt-proxy.toml"
    owner: root
    group: root
    mode: "0444"
  notify: Restart dnscrypt-proxy

- name: Configure allowed-names.txt
  ansible.builtin.template:
    src: allowed-names.txt.j2
    dest: "{{ dnscrypt_proxy_conf_dir }}/allowed-names.txt"
    owner: root
    group: root
    mode: "0444"
  when:
    - dnscrypt_proxy.allowed_names is defined
    - dnscrypt_proxy.allowed_names is iterable
  notify: Restart dnscrypt-proxy

- name: Configure blocked-ips.txt
  ansible.builtin.template:
    src: blocked-ips.txt.j2
    dest: "{{ dnscrypt_proxy_conf_dir }}/blocked-ips.txt"
    owner: root
    group: root
    mode: "0444"
  notify: Restart dnscrypt-proxy

- name: Configure forwarding-rules.txt
  ansible.builtin.template:
    src: forwarding-rules.txt.j2
    dest: "{{ dnscrypt_proxy_conf_dir }}/forwarding-rules.txt"
    owner: root
    group: root
    mode: "0444"
  when:
    - dnscrypt_proxy.forwarding_rules is defined
    - dnscrypt_proxy.forwarding_rules is iterable
  notify: Restart dnscrypt-proxy

- name: Configure cloaking-rules.txt
  ansible.builtin.template:
    src: cloaking-rules.txt.j2
    dest: "{{ dnscrypt_proxy_conf_dir }}/cloaking-rules.txt"
    owner: root
    group: root
    mode: "0444"
  when:
    - dnscrypt_proxy.cloaking_rules is defined
    - dnscrypt_proxy.cloaking_rules is iterable
  notify: Restart dnscrypt-proxy
