---
- name: Remove dnscrypt-proxy package
  ansible.builtin.apt:
    name: dnscrypt-proxy
    state: absent
  tags:
    - dnscrypt-proxy

- name: Check dnscrypt-proxy version
  ansible.builtin.command: dnscrypt-proxy --version
  changed_when: false
  register: installed_version
  tags:
    - dnscrypt-proxy

- name: Install dnscrypt-proxy
  when: installed_version.stdout != dnscrypt_proxy.version
        and not ansible_check_mode
  tags:
    - dnscrypt-proxy
  block:
    - name: Download dnscrypt-proxy
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: /tmp
        owner: root
        group: root
        mode: 0644

    - name: Extract tarball
      ansible.builtin.unarchive:
        src: "/tmp/{{ tarball }}"
        dest: /tmp
        remote_src: true

    - name: Copy binary to /usr/sbin/dnscrypt_proxy
      ansible.builtin.copy:
        src: "/tmp/linux-{{ arch }}/dnscrypt-proxy"
        dest: /usr/sbin/dnscrypt-proxy
        remote_src: true
        owner: root
        group: root
        mode: 0755

    - name: Delete both unpacked directory and tarball
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/linux-{{ arch }}"
        - "/tmp/{{ tarball }}"

- name: Configure systemd service file
  ansible.builtin.template:
    src: dnscrypt-proxy.service.j2
    dest: /etc/systemd/system/dnscrypt-proxy.service
    owner: root
    group: root
    mode: 0755
  notify: Restart dnscrypt-proxy
  tags:
    - dnscrypt-proxy
