---
- name: install iptables package
  apt:
    name: iptables
    state: present
  tags:
    - firewall

- name: provision iptables.service
  template:
    src: iptables.service.j2
    dest: /etc/systemd/system/iptables.service
    owner: root
    group: root
    mode: 0400
  notify: daemon-reload
  tags:
    - firewall

- name: configure iptables
  template:
    src: iptables-rules.j2
    dest: /usr/local/sbin/iptables-rules
    owner: root
    group: root
    mode: 0700
  notify: iptables
  tags:
    - firewall

