---
- name: Set facts
  ansible.builtin.set_fact:
    ip: "{{ ansible_default_ipv4.address }}"
    subnet: "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ansible.utils.ipaddr('net') }}"
    broadcast: "{{ ansible_default_ipv4.broadcast }}"
    interface: "{{ ansible_default_ipv4.interface }}"
  tags:
    - firewall

- name: Install iptables package
  ansible.builtin.apt:
    name: iptables
    state: present
  tags:
    - firewall

- name: Configure iptables
  ansible.builtin.template:
    src: iptables-rules.j2
    dest: /usr/local/sbin/iptables-rules
    owner: root
    group: root
    mode: 0700
  notify: Restart iptables
  tags:
    - firewall

- name: Configure iptables.service
  ansible.builtin.template:
    src: iptables.service.j2
    dest: /etc/systemd/system/iptables.service
    owner: root
    group: root
    mode: 0400
  notify: Daemon-reload
  tags:
    - firewall
