---
- name: Harden through sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ sysctl_file }}"
    state: present
  loop:
    "{{ sysctl_options }}"
  tags:
    - sysctl
