---
- name: Harden through sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ sysctl_file }}"
    state: present
  loop:
    "{{ sysctl_options }}"
  tags:
    - sysctl

- name: Remove other sysctl.d
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/sysctl.d/98-rpi.conf
  tags:
    - sysctl
