---
- name: Restart dnscrypt-proxy
  ansible.builtin.systemd:
    name: dnscrypt-proxy
    daemon-reload: true
    state: restarted

- name: Generate blocked names
  ansible.builtin.command: "{{ blocked_names_generator_helper_path }}"
  notify:
    - dnscrypt-proxy
