---
- name: install necessary packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  tags:
    - base

- name: remove unwanted packages
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ absent_packages }}"
  tags:
    - base

- name: set machine hostname
  hostname:
    name: "{{ network.hostname }}"
  tags:
    - base

- name: setup sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd
  tags:
    - base

- name: set hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    attr: +i
  tags:
    - base

- name: setup correct time
  file:
    src: /usr/share/zoneinfo/Europe/Prague
    dest: /etc/localtime
    force: yes
    state: link
  tags:
    - base

- name: setup locales
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - generate locales
  loop:
    - { src: locale.gen.j2, dest: /etc/locale.gen }
    - { src: default.locale.j2, dest: /etc/default/locale }
  tags:
    - base

- name: setup resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    attr: +i
  tags:
    - base

- name: prepare mount points
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ mount.points }}"
  when: mount.points is defined
  tags:
    - base

- name: disable unwanted services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: "{{ disabled_services }}"
  when: disabled_services is defined
  tags:
    - base
