---
- name: Install necessary packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  tags:
    - base

- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ absent_packages }}"
  tags:
    - base

- name: Setup boot/config.txt
  ansible.builtin.template:
    src: boot-config.txt.j2
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0755
  tags:
    - base

- name: Set machine hostname
  ansible.builtin.hostname:
    name: "{{ network.hostname }}"
  tags:
    - base

- name: Setup sshd
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Restart sshd
  tags:
    - base

- name: Set hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    attr: +i
  tags:
    - base

- name: Setup correct time
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Europe/Prague
    dest: /etc/localtime
    force: true
    state: link
  tags:
    - base

- name: Setup locales
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  notify: Generate locales
  loop:
    - {src: locale.gen.j2, dest: /etc/locale.gen}
    - {src: default.locale.j2, dest: /etc/default/locale}
  tags:
    - base

- name: Setup resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    attr: +i
  tags:
    - base

- name: Prepare mount points
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ mount.points }}"
  when: mount.points is defined
  tags:
    - base

- name: Disable unwanted services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ disabled_services }}"
  when: disabled_services is defined
  tags:
    - base
